In [4]:
kosdaq.empty

True

In [5]:
import datetime

start_date = datetime.date(2023, 1, 1)
end_date = datetime.date(2023, 4, 1)

date_list = []
current_date = start_date
while current_date <= end_date:
    date_list.append(current_date.strftime("%Y%m%d"))
    current_date += datetime.timedelta(days=1)

print(date_list)

['20230101', '20230102', '20230103', '20230104', '20230105', '20230106', '20230107', '20230108', '20230109', '20230110', '20230111', '20230112', '20230113', '20230114', '20230115', '20230116', '20230117', '20230118', '20230119', '20230120', '20230121', '20230122', '20230123', '20230124', '20230125', '20230126', '20230127', '20230128', '20230129', '20230130', '20230131', '20230201', '20230202', '20230203', '20230204', '20230205', '20230206', '20230207', '20230208', '20230209', '20230210', '20230211', '20230212', '20230213', '20230214', '20230215', '20230216', '20230217', '20230218', '20230219', '20230220', '20230221', '20230222', '20230223', '20230224', '20230225', '20230226', '20230227', '20230228', '20230301', '20230302', '20230303', '20230304', '20230305', '20230306', '20230307', '20230308', '20230309', '20230310', '20230311', '20230312', '20230313', '20230314', '20230315', '20230316', '20230317', '20230318', '20230319', '20230320', '20230321', '20230322', '20230323', '20230324', '20230325', '20230326', '20230327', '20230328', '20230329', '20230330', '20230331', '20230401']

In [6]:
import pandas as pd
rapid = pd.DataFrame()
for date in date_list:
    temp = get_rapid_ticker(date, date)
    if temp.empty == False:
        temp['date'] = date
        rapid = pd.concat([rapid, temp], axis=0)
        print(date, 'finish')

20230102 finish
20230103 finish
20230104 finish
20230105 finish
20230106 finish
20230109 finish
20230110 finish
20230111 finish
20230112 finish
20230113 finish
20230116 finish
20230117 finish
20230118 finish
20230119 finish
20230120 finish
20230125 finish
20230126 finish
20230127 finish
20230130 finish
20230131 finish
20230201 finish
20230202 finish
20230203 finish
20230206 finish
20230207 finish
20230208 finish
20230209 finish
20230210 finish
20230213 finish
20230214 finish
20230215 finish
20230216 finish
20230217 finish
20230220 finish
20230221 finish
20230222 finish
20230223 finish
20230224 finish
20230227 finish
20230228 finish
20230302 finish
20230303 finish
20230306 finish
20230307 finish
20230308 finish
20230309 finish
20230310 finish
20230313 finish
20230314 finish
20230315 finish
20230316 finish
20230317 finish
20230320 finish
20230321 finish
20230322 finish
20230323 finish
20230324 finish
20230327 finish
20230328 finish
20230329 finish
20230330 finish
20230331 finish

In [10]:
rapid.to_excel('rapid_01_03.xlsx', encoding='utf-8')

In [13]:
rapid.reset_index(inplace=True)

In [16]:
dict(rapid['티커'].value_counts())

{'108860': 7,
 '234920': 7,
 '402030': 7,
 '208370': 6,
 '064480': 6,
 '277810': 5,
 '389500': 5,
 '051980': 5,
 '277070': 5,
 '407400': 5,
 '024850': 5,
 '082660': 5,
 '106520': 4,
 '086520': 4,
 '086960': 4,
 '041020': 4,
 '037370': 4,
 '348340': 4,
 '394280': 4,
 '417860': 4,
 '318000': 3,
 '093640': 3,
 '290520': 3,
 '315640': 3,
 '032685': 3,
 '417010': 3,
 '049950': 3,
 '246720': 3,
 '347700': 3,
 '320000': 3,
 '060230': 3,
 '148780': 3,
 '065420': 3,
 '322180': 3,
 '254490': 3,
 '304100': 3,
 '198940': 3,
 '357550': 3,
 '317830': 3,
 '189330': 3,
 '114190': 3,
 '300120': 3,
 '347860': 3,
 '121800': 3,
 '207760': 3,
 '037950': 3,
 '175250': 3,
 '115500': 3,
 '082800': 3,
 '419530': 3,
 '016790': 3,
 '205470': 3,
 '357880': 2,
 '322310': 2,
 '376180': 2,
 '123420': 2,
 '214610': 2,
 '338220': 2,
 '216080': 2,
 '054630': 2,
 '009520': 2,
 '389020': 2,
 '042600': 2,
 '099750': 2,
 '053060': 2,
 '094480': 2,
 '058970': 2,
 '127980': 2,
 '237820': 2,
 '095500': 2,
 '096630': 2,
 '071670': 2,
 '099390': 2,
 '032790': 2,
 '08537M': 2,
 '073570': 2,
 '294140': 2,
 '383310': 2,
 '227950': 2,
 '288980': 2,
 '101670': 2,
 '373200': 2,
 '368770': 2,
 '418550': 2,
 '214680': 2,
 '270520': 2,
 '065370': 2,
 '043090': 2,
 '122690': 2,
 '090150': 2,
 '417840': 2,
 '123010': 2,
 '084180': 2,
 '072520': 2,
 '058610': 2,
 '211270': 2,
 '096610': 2,
 '065660': 2,
 '242040': 2,
 '101390': 2,
 '351320': 2,
 '053590': 2,
 '351330': 2,
 '389260': 2,
 '058450': 2,
 '031860': 2,
 '008290': 2,
 '352770': 2,
 '417180': 2,
 '380540': 2,
 '065650': 2,
 '900100': 2,
 '168360': 2,
 '347770': 2,
 '336060': 2,
 '047920': 2,
 '054920': 2,
 '009730': 2,
 '106240': 2,
 '032750': 2,
 '255440': 2,
 '024830': 2,
 '019570': 2,
 '220180': 2,
 '418420': 2,
 '360070': 2,
 '331520': 2,
 '036030': 2,
 '134580': 2,
 '006140': 2,
 '089530': 2,
 '217480': 2,
 '352910': 1,
 '108490': 1,
 '222080': 1,
 '299170': 1,
 '348370': 1,
 '007390': 1,
 '126600': 1,
 '054780': 1,
 '059090': 1,
 '125210': 1,
 '064090': 1,
 '065570': 1,
 '388050': 1,
 '425420': 1,
 '387310': 1,
 '261780': 1,
 '014100': 1,
 '365340': 1,
 '079950': 1,
 '137400': 1,
 '101730': 1,
 '067630': 1,
 '239610': 1,
 '309960': 1,
 '232140': 1,
 '258830': 1,
 '117670': 1,
 '303030': 1,
 '356890': 1,
 '066670': 1,
 '024810': 1,
 '174900': 1,
 '115160': 1,
 '368600': 1,
 '305090': 1,
 '344860': 1,
 '068760': 1,
 '200710': 1,
 '028080': 1,
 '024880': 1,
 '079370': 1,
 '317120': 1,
 '372800': 1,
 '028300': 1,
 '259630': 1,
 '042940': 1,
 '140410': 1,
 '250060': 1,
 '041910': 1,
 '043590': 1,
 '171090': 1,
 '114630': 1,
 '038110': 1,
 '323990': 1,
 '270660': 1,
 '148150': 1,
 '101170': 1,
 '170920': 1,
 '290670': 1,
 '073190': 1,
 '065350': 1,
 '129920': 1,
 '051780': 1,
 '403870': 1,
 '372170': 1,
 '101330': 1,
 '282720': 1,
 '294090': 1,
 '256940': 1,
 '263600': 1,
 '049070': 1,
 '101360': 1,
 '321260': 1,
 '137080': 1,
 '036180': 1,
 '036540': 1,
 '312610': 1,
 '060280': 1,
 '281740': 1,
 '029480': 1,
 '371950': 1,
 '019660': 1,
 '088130': 1,
 '056080': 1,
 '091580': 1,
 '101680': 1,
 '142760': 1,
 '247540': 1,
 '241690': 1,
 '217620': 1,
 '051490': 1,
 '199820': 1,
 '022100': 1,
 '153490': 1,
 '250930': 1,
 '246710': 1,
 '046970': 1,
 '294630': 1,
 '227610': 1,
 '000250': 1,
 '121850': 1,
 '950110': 1,
 '040300': 1,
 '065150': 1,
 '088290': 1,
 '196490': 1,
 '050090': 1,
 '079810': 1,
 '115440': 1,
 '124500': 1,
 '376930': 1,
 '112040': 1,
 '144960': 1,
 '368970': 1,
 '090360': 1,
 '297570': 1,
 '340440': 1,
 '086890': 1,
 '200350': 1,
 '019770': 1,
 '187790': 1,
 '296640': 1,
 '263800': 1,
 '239340': 1,
 '051160': 1,
 '224060': 1,
 '301300': 1,
 '291810': 1,
 '050960': 1,
 '362320': 1,
 '257720': 1,
 '098460': 1,
 '031510': 1,
 '344050': 1,
 '039010': 1,
 '053050': 1,
 '032620': 1,
 '053270': 1,
 '263700': 1,
 '053800': 1,
 '036810': 1,
 '041190': 1,
 '091440': 1,
 '049080': 1,
 '069410': 1,
 '062970': 1,
 '063170': 1,
 '391710': 1,
 '115530': 1,
 '206640': 1,
 '131400': 1,
 '037440': 1,
 '037350': 1,
 '048410': 1,
 '042510': 1,
 '033320': 1,
 '031980': 1,
 '204630': 1,
 '317690': 1,
 '273060': 1,
 '046390': 1,
 '223250': 1,
 '328130': 1,
 '053950': 1,
 '337930': 1,
 '317530': 1,
 '058110': 1,
 '054930': 1,
 '304840': 1,
 '095700': 1,
 '339950': 1,
 '161570': 1,
 '026040': 1,
 '015710': 1,
 '376300': 1,
 '040160': 1,
 '043910': 1,
 '053290': 1,
 '388720': 1,
 '050860': 1,
 '425290': 1,
 '090710': 1,
 '089140': 1,
 '284620': 1,
 '036690': 1,
 '314140': 1,
 '365590': 1,
 '104200': 1,
 '063080': 1,
 '067920': 1,
 '049630': 1,
 '032680': 1,
 '412350': 1,
 '086900': 1,
 '048550': 1,
 '063440': 1,
 '092600': 1,
 '099440': 1,
 '377480': 1,
 '016100': 1,
 '049480': 1,
 '053350': 1,
 '039310': 1,
 '121600': 1,
 '080720': 1,
 '039290': 1,
 '328380': 1,
 '331380': 1,
 '397500': 1,
 '080220': 1,
 '130740': 1,
 '323280': 1,
 '363260': 1,
 '200470': 1,
 '355150': 1,
 '411080': 1,
 '067080': 1,
 '140070': 1,
 '331920': 1,
 '041590': 1,
 '064550': 1,
 '033160': 1,
 '097800': 1,
 '388790': 1,
 '204610': 1,
 '200230': 1,
 '367000': 1,
 '123840': 1,
 '190650': 1,
 '196450': 1,
 '187270': 1,
 '094940': 1,
 '389140': 1,
 '425040': 1,
 '214370': 1,
 '099320': 1,
 '419540': 1,
 '276040': 1,
 '268600': 1,
 '039740': 1,
 '206400': 1,
 '035610': 1,
 '321820': 1,
 '045970': 1,
 '164060': 1,
 '258790': 1,
 '042040': 1,
 '226330': 1,
 '279600': 1,
 '900280': 1,
 '408900': 1,
 '033560': 1,
 '303530': 1,
 '227100': 1,
 '089150': 1,
 '317870': 1,
 '211050': 1,
 '399720': 1,
 '046440': 1,
 '198080': 1,
 '291230': 1,
 '025770': 1,
 '419050': 1,
 '195990': 1}

In [19]:
rapid[rapid['등락률'] > 15]

,티커,종목명,시가,종가,변동폭,등락률,거래량,거래대금,date
1,080720,한국유니온제약,7150,8250,1100,15.38,5861630,47398086920,20230102
2,058110,멕아이씨에스,5860,6910,1050,17.92,15802121,109342862210,20230102
3,317530,캐리소프트,7330,8650,1320,18.01,2631897,22128343790,20230102
4,337930,브랜드엑스코퍼레이션,4770,5760,990,20.75,3571399,20129758250,20230102
5,207760,미스터블루,3280,4000,720,21.95,28431606,109636636775,20230102
...,...,...,...,...,...,...,...,...,...
615,290520,신도기연,6780,8100,1320,19.47,13708033,108547859780,20230331
616,234920,자이글,19780,24050,4270,21.59,4348542,102799730500,20230331
617,388050,지투파워,9470,11970,2500,26.40,49660118,552139544140,20230331
618,195990,에이비프로바이오,409,531,122,29.83,34638089,17232070517,20230331
619,096610,알에프세미,5530,7180,1650,29.84,5439869,37665306390,20230331